# Generated by Django 4.2.6 on 2025-01-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_userprofile_user_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user_id',
        ),
    ]
