# Generated by Django 4.2.6 on 2025-01-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_rename_username_userprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
