# Generated by Django 4.2.6 on 2024-10-27 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('ended', 'Ended')], max_length=20)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_player_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
